POST https://full-stack-open-part3-phonebook-weathered-silence-8650.fly.dev/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "99-99-9999999",
    "dodgy": "some dodgy code"
}
